version: 1.2
workflows:
- name: BbCallGenotypes
  subclass: wdl
  primaryDescriptorPath: /wdls/pipelines/BbCallGenotypes.wdl
- name: BbCallOspC
  subclass: wdl
  primaryDescriptorPath: /wdls/workflows/BbCallOspC.wdl
- name: BbCallPlasmids
  subclass: wdl
  primaryDescriptorPath: /wdls/workflows/BbCallPlasmids.wdl
- name: BbCallRST
  subclass: wdl
  primaryDescriptorPath: /wdls/workflows/BbCallRST.wdl
